[package]
authors = ["Ricky Han <tectonic@rickyhan.com>"]
description = "fast datastore server for contiguous order book ticks"
exclude = ["db/*", "test/test-data/*"]
keywords = ["finance", "datastore", "database", "financial"]
repository = "https://github.com/rickyhan/tectonicdb"
license = "MIT"
name = "tectonicdb"
readme = "README.md"
edition = "2018"
version = "0.2.3"
autobins = false

[[bin]]
name = "tectonic-server"
path = "src/bin/server/main.rs"

[[bin]]
name = "tectonic-cli"
path = "src/bin/cli/main.rs"

[[bin]]
name = "dtfsplit"
path = "src/bin/dtfsplit/main.rs"

[[bin]]
name = "dtfcat"
path = "src/bin/dtfcat/main.rs"

[[bin]]
name = "dtfconcat"
path = "src/bin/dtfconcat/main.rs"

[dependencies]
bitflags = "1.0.4"
byteorder = "1.3.0"
chrono = "0.4"
circular-queue = "0.2.0"
clap = "~2.32"
config = "0.9"
csv = "1.0.5"
fern = "0.5"
futures = "0.1.14"
lazy_static = "1.2.0"
log = "0.4"
openssl-probe = "0.1.2"
reqwest = "0.9.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1.42"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-signal = "0.2.7"
indexmap = "1.0.2"

[dependencies.tempdir]
optional = true
version = "0.3.7"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.7.2"

[features]
default = ["gcs"]
gcs = ["tempdir"]

[lib]
crate-type = ["dylib", "rlib"]
name = "libtectonic"
path = "src/lib/lib.rs"
